### ISSUE TITLE
This app

### ISSUE THREAD

**Issue by MilanScherpen** [hteibler/eaton_srv#1]
Hello Hteibler,

Thank you for developing this app. I have a question, does the app still work properly? I see that the last changes made to the app date from February 2022. The plan I currently have is to buy the Homey pro early 2023 if this app is an option, no pressure :P. If the app works, are there any limitations to the system or is it possible to fully integrate the entire system. I am aware that you must have an SHC. 

I look forward to hearing from you and thank you in advance!

Greetings,

Milan Scherpen

**Comment by hteibler** [comment]
HI Milan
I know this is not Github style
but here you can find my latest version, also for docker 

https://drive.google.com/file/d/1PHVCgE7z_4JRN1qtJ78AGL8w9xqAK_Rs/view?usp=drive_link

feel free to test and use
it's still not finished
but I use it permanetly and its working as expected
best, herbert

**Comment by hteibler** [comment]
updated homezone support
https://drive.google.com/file/d/1lYa1UJGvLDTGX5UZ9DzFDo3Mt8wZEbVX/view?usp=drive_link

**Comment by hteibler** [comment]
moved to 
https://github.com/hteibler/eaton_docker

**Comment by MilanScherpen** [comment]
Thanks i will certainly try this :D!

**Comment by MilanScherpen** [comment]
Hello hteibler,

Since you are the developer of this app, I still want to try to reach you. Perhaps you know a solution to the problem described in the topic below. Thank you in advance!

https://community.homey.app/t/installing-cli-error/85440

Greetings.
